"""add error column to csvfile

Revision ID: 42875e74554c
Revises: e0f01560523f
Create Date: 2025-06-20 13:58:56.577363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42875e74554c'
down_revision: Union[str, Sequence[str], None] = 'e0f01560523f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csv_files', sa.Column('drive_distance', sa.Integer(), nullable=True))
    op.add_column('csv_files', sa.Column('drive_time', sa.Integer(), nullable=True))
    op.add_column('csv_files', sa.Column('error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('csv_files', 'error')
    op.drop_column('csv_files', 'drive_time')
    op.drop_column('csv_files', 'drive_distance')
    # ### end Alembic commands ###
