"""add status to csvfile

Revision ID: a4c66da34a8b
Revises: c97997f3d1ec
Create Date: 2025-06-19 18:06:18.436393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4c66da34a8b'
down_revision: Union[str, Sequence[str], None] = 'c97997f3d1ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csv_files', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('csv_files', 'status')
    # ### end Alembic commands ###
