"""Initial tables

Revision ID: c97997f3d1ec
Revises: 0fce9e1f225f
Create Date: 2025-06-19 05:12:18.621376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c97997f3d1ec'
down_revision: Union[str, Sequence[str], None] = '0fce9e1f225f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_content', sa.LargeBinary(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csv_files_filename'), 'csv_files', ['filename'], unique=False)
    op.create_index(op.f('ix_csv_files_id'), 'csv_files', ['id'], unique=False)
    op.create_index(op.f('ix_csv_files_username'), 'csv_files', ['username'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_csv_files_username'), table_name='csv_files')
    op.drop_index(op.f('ix_csv_files_id'), table_name='csv_files')
    op.drop_index(op.f('ix_csv_files_filename'), table_name='csv_files')
    op.drop_table('csv_files')
    # ### end Alembic commands ###
