"""Add username and user_id to csv_files

Revision ID: f35e1ec66a64
Revises: 
Create Date: 2025-06-19 04:10:13.187555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f35e1ec66a64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csv_files', sa.Column('username', sa.String(), nullable=True))
    op.add_column('csv_files', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_csv_files_username'), 'csv_files', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_csv_files_username'), table_name='csv_files')
    op.drop_column('csv_files', 'user_id')
    op.drop_column('csv_files', 'username')
    # ### end Alembic commands ###
